export const list = [
  {
    id: '2315315',
    parentId: '',
    status: 'ok',
    recurringStatus: 'ok',
    hits: '213',
    title: 'Старая Ладога: 1270 лет истории Отечества',
    isAdvertisement: false,
    isRepeated: false,
    GAID: null,
    startDate: '2023-05-06 07:45:00',
    endDate: '2023-05-06 19:30:00',
    minPrice: null,
    maxPrice: null,
    ordersNumber: 0,
    ticketsNumber: 0,
    repeatedData: {
      count: null,
      nearest: null,
      furthest: null,
    },
    ofertaLink: 'https://turekskurs.timepad.ru/event/oferta/2315315/',
    allowRegistration: false,
    categories: ['461'],
    address: {
      city: 'Санкт-Петербург',
      street: 'Пл. Ленина,6',
      text: 'Санкт-Петербург, Пл. Ленина,6',
      lat: '59.955737',
      lon: '30.356436',
    },
    contact_phone: '+79046397321',
    organization: {
      id: '57087',
      logo: 'https://ucare.timepad.ru/c6fb2ff8-883e-46cb-bca2-8c05b1ee49a2/-/preview/308x600/-/format/jpeg/',
      name: 'Автобусные экскурсии',
      description:
        'Авторские экскурсии выходного дня по Северо-Западу (исторические места, крепости, монастыри, туристические комплексы).\nУспешный опыт организации и проведения экскурсий более 20 лет.\n\n',
      pdAddress:
        '188661, Ленинградская область, Всеволожский район, п.Мурино, ул.Шоссе в Лаврики,д.59, корп.1, кв.658',
      pdEmail: 'travel.val@yandex.ru',
      inn: '471800508009',
      ogrn: null,
      workingTime: '10:00 - 18:00',
      shareLink: null,
      poster:
        'https://ucare.timepad.ru/41249879-fbef-4dd2-9c66-76d0a1375fb6/-/preview/308x600/-/format/jpeg/-/format/jpeg/poster_org_57087.jpg',
      socials: [
        {
          name: 'vk',
          url: '',
        },
        {
          name: 'facebook',
          url: '',
        },
        {
          name: 'twitter',
          url: '',
        },
        {
          name: 'telegram',
          url: '',
        },
        {
          name: 'instagram',
          url: '',
        },
        {
          name: 'web',
          url: '',
        },
      ],
      subscribers: 2,
      eventCount: null,
      isFavorite: false,
      contact_phone: '+79046397321',
    },
    isFavorite: false,
    order_mail: null,
    rating: null,
    startDateUnknown: false,
  },
  {
    id: '2406348',
    parentId: '',
    status: 'ok',
    recurringStatus: 'ok',
    hits: '209',
    title: 'Мастерская «NLP 101» ',
    isAdvertisement: false,
    isRepeated: false,
    GAID: null,
    startDate: '2023-05-06 11:00:00',
    endDate: '2023-05-06 19:00:00',
    minPrice: 0,
    maxPrice: 0,
    ordersNumber: 0,
    ticketsNumber: 0,
    repeatedData: {
      count: null,
      nearest: null,
      furthest: null,
    },
    ofertaLink: 'https://nlp-ps.timepad.ru/event/oferta/2406348/',
    allowRegistration: true,
    categories: ['2465'],
    address: {
      city: 'Санкт-Петербург',
      street: 'набережная Кутузова, 22 ( Особняк Серебряковой)',
      text: 'Санкт-Петербург, набережная Кутузова, 22 ( Особняк Серебряковой)',
      lat: '59.948803',
      lon: '30.341704',
    },
    contact_phone: '+79944048018',
    organization: {
      id: '338850',
      logo: 'https://ucare.timepad.ru/4a79bf46-7ab8-45c7-b88b-bc7aba060085/-/preview/308x600/-/format/jpeg/',
      name: 'NLP P.S.',
      description: 'Кружок по обработке естественного языка в ЕУСПб',
      pdAddress: '191187, город Санкт-Петербург, улица Гагаринская, дом 6/1',
      pdEmail: 'sosnovskaya.yanka@mail.ru',
      inn: null,
      ogrn: null,
      workingTime: '10:00 - 18:00',
      shareLink: null,
      poster: null,
      socials: [
        {
          name: 'vk',
          url: '',
        },
        {
          name: 'facebook',
          url: '',
        },
        {
          name: 'twitter',
          url: '',
        },
        {
          name: 'telegram',
          url: '',
        },
        {
          name: 'instagram',
          url: '',
        },
        {
          name: 'web',
          url: '',
        },
      ],
      subscribers: 0,
      eventCount: null,
      isFavorite: false,
      contact_phone: '+79944048018',
    },
    isFavorite: false,
    order_mail: false,
    rating: null,
    startDateUnknown: false,
  },
  {
    id: '2405367',
    parentId: '',
    status: 'ok',
    recurringStatus: 'ok',
    hits: '229',
    title: 'Экскурсия в ЦВЗ Манеж "Первая позиция. Русский балет"',
    isAdvertisement: false,
    isRepeated: false,
    GAID: 'G-7N1543B5KC',
    startDate: '2023-05-06 12:00:00',
    endDate: '2023-05-06 13:30:00',
    minPrice: 2000,
    maxPrice: 2500,
    ordersNumber: 0,
    ticketsNumber: 0,
    repeatedData: {
      count: null,
      nearest: null,
      furthest: null,
    },
    ofertaLink: 'https://sloi-peterburga.timepad.ru/event/oferta/2405367/',
    allowRegistration: true,
    categories: ['461'],
    address: {
      city: 'Санкт-Петербург',
      street: 'Исаакиевская пл., 1',
      text: 'Санкт-Петербург, Исаакиевская пл., 1',
      lat: '59.934245',
      lon: '30.303301',
    },
    contact_phone: '+79618020005',
    organization: {
      id: '323691',
      logo: 'https://ucare.timepad.ru/c4c7a75f-6656-4c7b-8601-785c4029096c/-/preview/308x600/-/format/jpeg/',
      name: 'SLOI Петербурга',
      description:
        'На экскурсию в музей за смыслом!\nЭкскурсии по Петербургу в мини-группах с философами, искусствоведами, историками и журналистами.',
      pdAddress: '196240, г Санкт-Петербург, ул Варшавская, д 71, кв 46',
      pdEmail: 'sloi.piter@gmail.com',
      inn: '7820316156',
      ogrn: '1089847354794',
      workingTime: '10:00 - 20:00',
      shareLink: null,
      poster:
        'https://ucare.timepad.ru/83666a58-2e07-435c-a901-96b51cf8c77f/-/preview/308x600/-/format/jpeg/-/format/jpeg/poster_org_323691.jpg',
      socials: [
        {
          name: 'vk',
          url: 'https://vk.com/sloi.piter',
        },
        {
          name: 'facebook',
          url: '',
        },
        {
          name: 'twitter',
          url: '',
        },
        {
          name: 'telegram',
          url: 'https://t.me/sloipiter',
        },
        {
          name: 'instagram',
          url: '',
        },
        {
          name: 'web',
          url: 'https://sloipiter.ru/',
        },
      ],
      subscribers: 5,
      eventCount: null,
      isFavorite: false,
      contact_phone: '+79618020005',
    },
    isFavorite: false,
    order_mail: false,
    rating: null,
    startDateUnknown: false,
  },
  {
    id: '2403635',
    parentId: '',
    status: 'ok',
    recurringStatus: 'ok',
    hits: '168',
    title: 'АРХИТЕКТУРНОЕ РАЗНООБРАЗИЕ КРАСНОГВАРДЕЙСКОГО РАЙОНА | ЭКСКУРСИЯ',
    isAdvertisement: false,
    isRepeated: false,
    GAID: null,
    startDate: '2023-05-06 12:00:00',
    endDate: '2023-05-06 14:30:00',
    minPrice: 0,
    maxPrice: 0,
    ordersNumber: 0,
    ticketsNumber: 0,
    repeatedData: {
      count: null,
      nearest: null,
      furthest: null,
    },
    ofertaLink:
      'https://shkaf--art-rezidentsiya-b.timepad.ru/event/oferta/2403635/',
    allowRegistration: true,
    categories: ['461'],
    address: {
      city: 'Санкт-Петербург',
      street: 'Таллинская улица, 6',
      text: 'Санкт-Петербург, Таллинская улица, 6',
      lat: '59.923090',
      lon: '30.408655',
    },
    contact_phone: '+78122268780',
    organization: {
      id: '190686',
      logo: 'https://ucare.timepad.ru/b2898f1e-bafd-4aaf-8b9e-07a934481433/',
      name: 'ШКАФ| Библиотека | Арт-резиденция',
      description: '',
      pdAddress: 'ул. Маршала Тухачевского, д.31Б',
      pdEmail: 'shkaflib@kr-cbs.ru',
      inn: null,
      ogrn: null,
      workingTime: '12:00 - 20:00',
      shareLink: null,
      poster:
        'https://ucare.timepad.ru/42fa22d1-65be-429c-b606-50f98136b298/-/format/jpeg/poster_org_190686.jpg',
      socials: [
        {
          name: 'vk',
          url: 'https://vk.com/shkaflib',
        },
        {
          name: 'facebook',
          url: '',
        },
        {
          name: 'twitter',
          url: '',
        },
        {
          name: 'telegram',
          url: '',
        },
        {
          name: 'instagram',
          url: '',
        },
        {
          name: 'web',
          url: '',
        },
      ],
      subscribers: 59,
      eventCount: null,
      isFavorite: false,
      contact_phone: '+78122268780',
    },
    isFavorite: false,
    order_mail: null,
    rating: null,
    startDateUnknown: false,
  },
  {
    id: '2385980',
    parentId: '',
    status: 'ok',
    recurringStatus: 'ok',
    hits: '116',
    title: 'Мастер-класс "Бабушкин сад"',
    isAdvertisement: false,
    isRepeated: false,
    GAID: null,
    startDate: '2023-05-06 12:00:00',
    endDate: '2023-05-06 14:00:00',
    minPrice: 0,
    maxPrice: 0,
    ordersNumber: 0,
    ticketsNumber: 0,
    repeatedData: {
      count: null,
      nearest: null,
      furthest: null,
    },
    ofertaLink:
      'https://tsentralnaya-biblio-2021.timepad.ru/event/oferta/2385980/',
    allowRegistration: true,
    categories: ['525'],
    address: {
      city: 'Санкт-Петербург',
      street: 'ул. Варшавская, д. 37, к. 1',
      text: 'Санкт-Петербург, ул. Варшавская, д. 37, к. 1',
      lat: '59.859818',
      lon: '30.313541',
    },
    contact_phone: '+79119861044',
    organization: {
      id: '256831',
      logo: 'https://ucare.timepad.ru/468e0de2-7b3e-4e95-aab4-4a4ed304dbb7/-/preview/308x600/-/format/jpeg/',
      name: 'Центральная библиотека им. К.Г.Паустовского',
      description:
        '  Центральная библиотека имени К. Г. Паустовского – территория словесности. Статус библиотеки определяет разнообразный характер социокультурной деятельности, но приоритетным является изучение и продвижение мировой классической литературы, лучших современных писателей. Особое внимание уделяется жизни и творчеству Константина Георгиевича Паустовского, чье имя библиотека носит с 1997 года.\n     Здесь проходят творческие встречи, литературно-музыкальные вечера, выставки, мастер -классы. Центральная библиотека является постоянным участником городских фестивалей и акций: «Читай всегда, читай везде!», «Как пройти в библиотеку?» «Петербургские разночтения», «Книжные аллеи», «Живые улицы».',
      pdAddress: 'Санкт-Петербург, ул. Варшавская д.37, к.1',
      pdEmail: 'paustovsky@cbs-msk.ru',
      inn: null,
      ogrn: null,
      workingTime: '10:00 - 21:00',
      shareLink: null,
      poster:
        'https://ucare.timepad.ru/4cd08403-c34c-45b8-98a6-bfa97fd6a193/-/preview/308x600/-/format/jpeg/-/format/jpeg/poster_org_256831.jpg',
      socials: [
        {
          name: 'vk',
          url: 'https://vk.com/bibliolight',
        },
        {
          name: 'facebook',
          url: '',
        },
        {
          name: 'twitter',
          url: '',
        },
        {
          name: 'telegram',
          url: '',
        },
        {
          name: 'instagram',
          url: 'https://www.instagram.com/lib_paustovsky/https://ucare.timepad.ru/06925bc2-476a-40a4-b8a6-8ccb14a3a75d/-/preview/308x600/-/format/jpeg/-/preview/308x600/-/format/jpeg/logo_org_256831.jpg',
        },
        {
          name: 'web',
          url: 'https://www.cbs-msk.ru/centralnaya-biblioteka',
        },
      ],
      subscribers: 4,
      eventCount: null,
      isFavorite: false,
      contact_phone: '+79119861044',
    },
    isFavorite: false,
    order_mail: null,
    rating: null,
    startDateUnknown: false,
  },
  {
    id: '2406259',
    parentId: '',
    status: 'ok',
    recurringStatus: 'ok',
    hits: '63',
    title: 'Tinder-бранч',
    isAdvertisement: false,
    isRepeated: false,
    GAID: null,
    startDate: '2023-05-06 13:00:00',
    endDate: '2023-05-06 15:30:00',
    minPrice: 1400,
    maxPrice: 1400,
    ordersNumber: 0,
    ticketsNumber: 0,
    repeatedData: {
      count: null,
      nearest: null,
      furthest: null,
    },
    ofertaLink: 'https://rightpeopleunion.timepad.ru/event/oferta/2406259/',
    allowRegistration: true,
    categories: ['453'],
    address: {
      city: 'Санкт-Петербург',
      street: 'Ресторан Tetto\r\nБольшой проспект П.С., 84',
      text: 'Санкт-Петербург, Ресторан Tetto\r\nБольшой проспект П.С., 84',
      lat: '59.961868',
      lon: '30.300579',
    },
    contact_phone: '+79867442039',
    organization: {
      id: '311352',
      logo: 'https://ucare.timepad.ru/6a88e0b3-7995-400e-9abe-45602bd47a0e/-/preview/308x600/-/format/jpeg/',
      name: 'rightpeopleunion',
      description:
        'Наше сообщество проводит встречи для новых знакомств, митапы, квартирники, пикники, групповые сессии с психологом. Присоединяйтесь!',
      pdAddress:
        'обл. Нижегородская, р-н Богородский, г. Богородск, ул. Туркова, д. 6а, кв. 90',
      pdEmail: 'kristina.silaeva99@gmail.com',
      inn: '524507700444',
      ogrn: null,
      workingTime: '10:00 - 18:00',
      shareLink: null,
      poster: null,
      socials: [
        {
          name: 'vk',
          url: '',
        },
        {
          name: 'facebook',
          url: '',
        },
        {
          name: 'twitter',
          url: '',
        },
        {
          name: 'telegram',
          url: 'https://t.me/rightpeopleunion',
        },
        {
          name: 'instagram',
          url: '',
        },
        {
          name: 'web',
          url: '',
        },
      ],
      subscribers: 0,
      eventCount: null,
      isFavorite: false,
      contact_phone: '+79867442039',
    },
    isFavorite: false,
    order_mail: null,
    rating: null,
    startDateUnknown: false,
  },
  {
    id: '2395583',
    parentId: '',
    status: 'ok',
    recurringStatus: 'ok',
    hits: '61',
    title: 'Экскурсия на пивоварню Knightberg Brewery 18+',
    isAdvertisement: false,
    isRepeated: false,
    GAID: null,
    startDate: '2023-05-06 13:00:00',
    endDate: '2023-05-06 15:00:00',
    minPrice: 1000,
    maxPrice: 1000,
    ordersNumber: 0,
    ticketsNumber: 0,
    repeatedData: {
      count: null,
      nearest: null,
      furthest: null,
    },
    ofertaLink:
      'https://knightberg-brewery-event.timepad.ru/event/oferta/2395583/',
    allowRegistration: true,
    categories: ['461'],
    address: {
      city: 'Санкт-Петербург',
      street: 'Пироговская набережная 5/2',
      text: 'Санкт-Петербург, Пироговская набережная 5/2',
      lat: '59.956994',
      lon: '30.341353',
    },
    contact_phone: '+78127187888',
    organization: {
      id: '190678',
      logo: 'https://ucare.timepad.ru/2a661fb8-45ba-4c50-8f1f-8c5acf9154a1/',
      name: 'KNIGHTBERG BREWERY',
      description: '',
      pdAddress:
        '194044, г. Санкт-Петербург, Пироговская наб., дом 5/2, литера А, пом. 63-Н, офис 80',
      pdEmail: 'brand@redbrewer.com',
      inn: '7802690320',
      ogrn: '1197847110306',
      workingTime: '10:00 - 18:00',
      shareLink: null,
      poster: null,
      socials: [
        {
          name: 'vk',
          url: 'https://vk.com/knightberg',
        },
        {
          name: 'facebook',
          url: 'https://www.facebook.com/knightberg.brewery/',
        },
        {
          name: 'twitter',
          url: '',
        },
        {
          name: 'telegram',
          url: 'https://t.me/knightberg',
        },
        {
          name: 'instagram',
          url: '',
        },
        {
          name: 'web',
          url: '',
        },
      ],
      subscribers: 8,
      eventCount: null,
      isFavorite: false,
      contact_phone: '+78127187888',
    },
    isFavorite: false,
    order_mail: null,
    rating: null,
    startDateUnknown: false,
  },
  {
    id: '2394677',
    parentId: '',
    status: 'ok',
    recurringStatus: 'ok',
    hits: '58',
    title: 'Игротека',
    isAdvertisement: false,
    isRepeated: false,
    GAID: null,
    startDate: '2023-05-06 13:00:00',
    endDate: '2023-05-06 19:00:00',
    minPrice: 0,
    maxPrice: 0,
    ordersNumber: 0,
    ticketsNumber: 0,
    repeatedData: {
      count: null,
      nearest: null,
      furthest: null,
    },
    ofertaLink: 'https://biblioteka-lenina.timepad.ru/event/oferta/2394677/',
    allowRegistration: true,
    categories: ['524'],
    address: {
      city: 'Санкт-Петербург',
      street: 'ул. Воскова, д.2',
      text: 'Санкт-Петербург, ул. Воскова, д.2',
      lat: '59.957534',
      lon: '30.302950',
    },
    contact_phone: '+78122324062',
    organization: {
      id: '173509',
      logo: 'https://ucare.timepad.ru/a25756dd-a81f-4b0a-92de-1c2d8f476260/',
      name: 'Библиотека Ленина',
      description: '',
      pdAddress: 'ул. Воскова, д. 2',
      pdEmail: 'liblenina-reader@mail.ru',
      inn: null,
      ogrn: null,
      workingTime: '09:00 - 21:00',
      shareLink: null,
      poster: null,
      socials: [
        {
          name: 'vk',
          url: 'https://vk.com/liblenina',
        },
        {
          name: 'facebook',
          url: 'https://www.facebook.com/liblenina',
        },
        {
          name: 'twitter',
          url: '',
        },
        {
          name: 'telegram',
          url: '',
        },
        {
          name: 'instagram',
          url: 'https://www.instagram.com/liblenina/',
        },
        {
          name: 'web',
          url: 'https://pr-cbs.ru/liblenina',
        },
      ],
      subscribers: 67,
      eventCount: null,
      isFavorite: false,
      contact_phone: '+78122324062',
    },
    isFavorite: false,
    order_mail: null,
    rating: null,
    startDateUnknown: false,
  },
  {
    id: '2406295',
    parentId: '',
    status: 'ok',
    recurringStatus: 'ok',
    hits: '1034',
    title: 'Экскурсия «Пулковская обсерватория в годы войны 1941-1945» ',
    isAdvertisement: false,
    isRepeated: false,
    GAID: null,
    startDate: '2023-05-06 14:00:00',
    endDate: '2023-05-06 16:00:00',
    minPrice: 1150,
    maxPrice: 1150,
    ordersNumber: 0,
    ticketsNumber: 0,
    repeatedData: {
      count: null,
      nearest: null,
      furthest: null,
    },
    ofertaLink: 'https://gaoran.timepad.ru/event/oferta/2406295/',
    allowRegistration: true,
    categories: ['2465'],
    address: {
      city: 'Санкт-Петербург',
      street: 'Пулковское шоссе, д.65',
      text: 'Санкт-Петербург, Пулковское шоссе, д.65',
      lat: '59.770882',
      lon: '30.331633',
    },
    contact_phone: '+79312662887',
    organization: {
      id: '49842',
      logo: 'https://ucare.timepad.ru/c4e14c80-674f-43d5-8030-992105ddab86/',
      name: 'ФГБУН Главная (Пулковская) астрономическая обсерватория РАН',
      description:
        'Главная (Пулковская) астрономическая обсерватория Российской академии наук была основана в 1839 году по указу императора Николая  I и построена по проекту видного российского архитектора Александра Брюллова.\nГлавной составляющей интересной экскурсионной программы для посетителей Пулковской обсерватории является её Астрономический музей, экспонаты которого отражают историю развития российской астрономии XIX-XX веков. Музей расположен в Круглом и Меридианном залах Главного здания обсерватории.\nПервый музей Пулковской обсерватории («Музей старинных инструментов») был основан ещё в 1884 году и включал более 100 астрономических инструментов XVIII-XIX веков. Однако в годы Великой Отечественной войны многие экспонаты музея погибли. Настоящий музей и его экспозиция были заново возрождены уже в послевоенное время в 1967 году. Сегодня посетители могут ознакомиться с уникальными экспонатами музея - геодезическими инструментами, измерительной и вычислительной техникой, с оптикой крупнейших телескопов XIX-XX веков, собранием астрономических часов, портретами астрономов и ученых прошлых веков; увидеть центр Круглого зала, через который проходит знаменитый Пулковский меридиан.\nЭкскурсионная программа включает также знакомство посетителей с различными инструментами Обсерватории – телескопом-рефрактором на Центральной башне Главного здания, Большим Пулковским радиотелескопом, Солнечным телескопом, Нормальным астрографом, 26-дюймовым рефрактором и парком обсерватории. Ежегодно Обсерваторию посещает около 18 тысяч экскурсантов и гостей Санкт-Петербурга.\nГлавная (Пулковская) астрономическая обсерватория Российской Академии наук, оставаясь крупнейшим астрономическим учреждением России, Указом Президента Российской Федерации от 1998 года была включена в свод особо ценных объектов культурного наследия народов Российской Федерации и вошла в Список объектов всемирного наследия, находящихся под охраной ЮНЕСКО.\n\n',
      pdAddress: 'г Санкт-Петербург, Пулковское шоссе, д 65 к 1',
      pdEmail: 'pulkovoexc@gmail.com',
      inn: '7810207327',
      ogrn: '1037821018421',
      workingTime: '11:00 - 17:00',
      shareLink: null,
      poster: null,
      socials: [
        {
          name: 'vk',
          url: 'https://vk.com/pulex',
        },
        {
          name: 'facebook',
          url: '',
        },
        {
          name: 'twitter',
          url: '',
        },
        {
          name: 'telegram',
          url: '',
        },
        {
          name: 'instagram',
          url: '',
        },
        {
          name: 'web',
          url: 'http://www.gaoran.ru/',
        },
      ],
      subscribers: 157,
      eventCount: null,
      isFavorite: false,
      contact_phone: '+79312662887',
    },
    isFavorite: false,
    order_mail: false,
    rating: null,
    startDateUnknown: false,
  },
  {
    id: '2401331',
    parentId: '',
    status: 'ok',
    recurringStatus: 'ok',
    hits: '62',
    title: '«Можно ли встретить насекомых в космосе?»',
    isAdvertisement: false,
    isRepeated: false,
    GAID: 'G-6D8P62BQ7Z',
    startDate: '2023-05-06 14:00:00',
    endDate: '2023-05-06 15:00:00',
    minPrice: null,
    maxPrice: null,
    ordersNumber: 0,
    ticketsNumber: 0,
    repeatedData: {
      count: null,
      nearest: null,
      furthest: null,
    },
    ofertaLink: 'https://timiryazevka.timepad.ru/event/oferta/2401331/',
    allowRegistration: false,
    categories: ['379'],
    address: {
      city: 'Санкт-Петербург',
      street: 'ул. Шкапина, 6 (м. Балтийская)',
      text: 'Санкт-Петербург, ул. Шкапина, 6 (м. Балтийская)',
      lat: '59.907622',
      lon: '30.297021',
    },
    contact_phone: '+78122527289',
    organization: {
      id: '46352',
      logo: 'https://ucare.timepad.ru/e7a5f0ac-651d-44c4-8524-44706d8a6ff0/-/preview/308x600/-/format/jpeg/',
      name: 'Библиотека им. К.А. Тимирязева',
      description:
        'Современное и уютное книжное пространство, где регулярно проходят выставки фотографов и художников, лекции, мастер-классы, концерты, кинолектории, языковые курсы и фестивали.',
      pdAddress: 'ул. Шкапина, д.6',
      pdEmail: 'biblio01@lplib.ru',
      inn: null,
      ogrn: null,
      workingTime: '09:00 - 20:00',
      shareLink: null,
      poster:
        'https://ucare.timepad.ru/b709b204-38a4-4ff8-a589-36b5da53b185/-/format/jpeg/poster_org_46352.jpg',
      socials: [
        {
          name: 'vk',
          url: 'https://vk.com/timiriazevka',
        },
        {
          name: 'facebook',
          url: '',
        },
        {
          name: 'twitter',
          url: '',
        },
        {
          name: 'telegram',
          url: '',
        },
        {
          name: 'instagram',
          url: 'https://www.instagram.com/timiriazevka/?hl=ru',
        },
        {
          name: 'web',
          url: '',
        },
      ],
      subscribers: 80,
      eventCount: null,
      isFavorite: false,
      contact_phone: '+78122527289',
    },
    isFavorite: false,
    order_mail: null,
    rating: null,
    startDateUnknown: false,
  },
  {
    id: '2376427',
    parentId: '',
    status: 'ok',
    recurringStatus: 'ok',
    hits: '115',
    title:
      'Экскурсия в Эрмитаж с философом. "Голландцы VS Фламандцы. Рембрандт"',
    isAdvertisement: false,
    isRepeated: false,
    GAID: 'G-7N1543B5KC',
    startDate: '2023-05-06 14:30:00',
    endDate: '2023-05-06 16:30:00',
    minPrice: 1500,
    maxPrice: 2500,
    ordersNumber: 0,
    ticketsNumber: 0,
    repeatedData: {
      count: null,
      nearest: null,
      furthest: null,
    },
    ofertaLink: 'https://sloi-peterburga.timepad.ru/event/oferta/2376427/',
    allowRegistration: true,
    categories: ['461'],
    address: {
      city: 'Санкт-Петербург',
      street: 'Дворцовая пл, 2',
      text: 'Санкт-Петербург, Дворцовая пл, 2',
      lat: '59.940082',
      lon: '30.312814',
    },
    contact_phone: '+79618020005',
    organization: {
      id: '323691',
      logo: 'https://ucare.timepad.ru/c4c7a75f-6656-4c7b-8601-785c4029096c/-/preview/308x600/-/format/jpeg/',
      name: 'SLOI Петербурга',
      description:
        'На экскурсию в музей за смыслом!\nЭкскурсии по Петербургу в мини-группах с философами, искусствоведами, историками и журналистами.',
      pdAddress: '196240, г Санкт-Петербург, ул Варшавская, д 71, кв 46',
      pdEmail: 'sloi.piter@gmail.com',
      inn: '7820316156',
      ogrn: '1089847354794',
      workingTime: '10:00 - 20:00',
      shareLink: null,
      poster:
        'https://ucare.timepad.ru/83666a58-2e07-435c-a901-96b51cf8c77f/-/preview/308x600/-/format/jpeg/-/format/jpeg/poster_org_323691.jpg',
      socials: [
        {
          name: 'vk',
          url: 'https://vk.com/sloi.piter',
        },
        {
          name: 'facebook',
          url: '',
        },
        {
          name: 'twitter',
          url: '',
        },
        {
          name: 'telegram',
          url: 'https://t.me/sloipiter',
        },
        {
          name: 'instagram',
          url: '',
        },
        {
          name: 'web',
          url: 'https://sloipiter.ru/',
        },
      ],
      subscribers: 5,
      eventCount: null,
      isFavorite: false,
      contact_phone: '+79618020005',
    },
    isFavorite: false,
    order_mail: false,
    rating: null,
    startDateUnknown: false,
  },
  {
    id: '2396460',
    parentId: '',
    status: 'ok',
    recurringStatus: 'ok',
    hits: '57',
    title:
      'Французский разговорный клуб: dis-moi ta langue, et je te dirai comment tu penses',
    isAdvertisement: false,
    isRepeated: false,
    GAID: null,
    startDate: '2023-05-06 14:30:00',
    endDate: '2023-05-06 16:00:00',
    minPrice: 0,
    maxPrice: 0,
    ordersNumber: 0,
    ticketsNumber: 0,
    repeatedData: {
      count: null,
      nearest: null,
      furthest: null,
    },
    ofertaLink: 'https://otkrytaya-gostinaya.timepad.ru/event/oferta/2396460/',
    allowRegistration: true,
    categories: ['382'],
    address: {
      city: 'Санкт-Петербург',
      street: 'Литейный проспект, 17-19',
      text: 'Санкт-Петербург, Литейный проспект, 17-19',
      lat: '59.943629',
      lon: '30.348046',
    },
    contact_phone: '+78122727595',
    organization: {
      id: '69453',
      logo: 'https://ucare.timepad.ru/d96c3baf-3a71-48ef-9cdd-039a475e4cd9/-/preview/308x600/-/format/jpeg/',
      name: 'Открытая Гостиная',
      description:
        'Открытая гостиная — это творческое пространство Центральной библиотеки им. М.Ю. Лермонтова, где проходят бесплатные лекции, мастер-классы, выставки, есть удобные места для работы и учебы.\n',
      pdAddress: 'Литейный пр. 19',
      pdEmail: 'openlivinglib@gmail.com',
      inn: null,
      ogrn: null,
      workingTime: '09:00 - 20:00',
      shareLink: null,
      poster:
        'https://ucare.timepad.ru/1d3580f7-c1dc-456e-922d-cad40e4fcd35/-/preview/308x600/-/format/jpeg/-/format/jpeg/poster_org_69453.jpg',
      socials: [
        {
          name: 'vk',
          url: 'https://vk.com/open_living',
        },
        {
          name: 'facebook',
          url: '',
        },
        {
          name: 'twitter',
          url: '',
        },
        {
          name: 'telegram',
          url: '',
        },
        {
          name: 'instagram',
          url: '',
        },
        {
          name: 'web',
          url: '',
        },
      ],
      subscribers: 102,
      eventCount: null,
      isFavorite: false,
      contact_phone: '+78122727595',
    },
    isFavorite: false,
    order_mail: null,
    rating: null,
    startDateUnknown: false,
  },
  {
    id: '2390705',
    parentId: '',
    status: 'ok',
    recurringStatus: 'ok',
    hits: '1246',
    title: 'Автофикшн: как писать о себе любимом и не раздражать окружающих',
    isAdvertisement: false,
    isRepeated: false,
    GAID: null,
    startDate: '2023-05-06 15:00:00',
    endDate: '2023-05-06 16:15:00',
    minPrice: 0,
    maxPrice: 0,
    ordersNumber: 0,
    ticketsNumber: 0,
    repeatedData: {
      count: null,
      nearest: null,
      furthest: null,
    },
    ofertaLink: 'https://oxta8.timepad.ru/event/oferta/2390705/',
    allowRegistration: true,
    categories: ['462'],
    address: {
      city: 'Санкт-Петербург',
      street: 'Большеохтинский проспект, дом 8',
      text: 'Санкт-Петербург, Большеохтинский проспект, дом 8',
      lat: '59.951146',
      lon: '30.409212',
    },
    contact_phone: '+79045514757',
    organization: {
      id: '171605',
      logo: 'https://ucare.timepad.ru/1c714536-b029-42ab-8803-222c7b09efbe/-/preview/308x600/-/format/jpeg/',
      name: 'Библиотека им. В.В. Маяковского, Охта-8',
      description: '',
      pdAddress: 'Санкт-Петербург, Большеохтинский проспект, дом 8',
      pdEmail: 'bigoxta@gmail.com',
      inn: null,
      ogrn: null,
      workingTime: '10:00 - 22:00',
      shareLink: null,
      poster:
        'https://ucare.timepad.ru/62e9175e-dbd9-4dda-8538-3b91eda2a293/-/preview/308x600/-/format/jpeg/-/format/jpeg/poster_org_171605.jpg',
      socials: [
        {
          name: 'vk',
          url: 'https://vk.com/bigoxta8',
        },
        {
          name: 'facebook',
          url: '',
        },
        {
          name: 'twitter',
          url: '',
        },
        {
          name: 'telegram',
          url: '',
        },
        {
          name: 'instagram',
          url: '',
        },
        {
          name: 'web',
          url: '',
        },
      ],
      subscribers: 152,
      eventCount: null,
      isFavorite: false,
      contact_phone: '+79045514757',
    },
    isFavorite: false,
    order_mail: null,
    rating: null,
    startDateUnknown: false,
  },
  {
    id: '2408310',
    parentId: '',
    status: 'ok',
    recurringStatus: 'ok',
    hits: '785',
    title: 'Комикс-скрапбукинг ',
    isAdvertisement: false,
    isRepeated: false,
    GAID: null,
    startDate: '2023-05-06 15:00:00',
    endDate: '2023-05-06 17:00:00',
    minPrice: 0,
    maxPrice: 0,
    ordersNumber: 0,
    ticketsNumber: 0,
    repeatedData: {
      count: null,
      nearest: null,
      furthest: null,
    },
    ofertaLink: 'https://comix-library.timepad.ru/event/oferta/2408310/',
    allowRegistration: true,
    categories: ['524'],
    address: {
      city: 'Санкт-Петербург',
      street: '7-ая Красноармейская 30',
      text: 'Санкт-Петербург, 7-ая Красноармейская 30',
      lat: '59.911448',
      lon: '30.308816',
    },
    contact_phone: '+79214278910',
    organization: {
      id: '197458',
      logo: 'https://ucare.timepad.ru/3f6534d9-3e11-4086-b4c4-c397260daa0b/',
      name: 'Библиотека Комиксов ',
      description: '',
      pdAddress: '7-ая Красноармейская, д. 30',
      pdEmail: 'karandeev@lplib.ru',
      inn: null,
      ogrn: null,
      workingTime: '11:00 - 21:00',
      shareLink: null,
      poster: null,
      socials: [
        {
          name: 'vk',
          url: '',
        },
        {
          name: 'facebook',
          url: '',
        },
        {
          name: 'twitter',
          url: '',
        },
        {
          name: 'telegram',
          url: '',
        },
        {
          name: 'instagram',
          url: '',
        },
        {
          name: 'web',
          url: '',
        },
      ],
      subscribers: 26,
      eventCount: null,
      isFavorite: false,
      contact_phone: '+79214278910',
    },
    isFavorite: false,
    order_mail: null,
    rating: null,
    startDateUnknown: false,
  },
  {
    id: '2409279',
    parentId: '',
    status: 'ok',
    recurringStatus: 'ok',
    hits: '16',
    title: 'Концерт «Весна победы»',
    isAdvertisement: false,
    isRepeated: false,
    GAID: null,
    startDate: '2023-05-06 15:00:00',
    endDate: '2023-05-06 16:30:00',
    minPrice: 0,
    maxPrice: 0,
    ordersNumber: 0,
    ticketsNumber: 0,
    repeatedData: {
      count: null,
      nearest: null,
      furthest: null,
    },
    ofertaLink: 'https://liblist.timepad.ru/event/oferta/2409279/',
    allowRegistration: true,
    categories: ['460'],
    address: {
      city: 'Санкт-Петербург',
      street:
        'г. Санкт-Петербург, п. Шушары, Московское шоссе, дом 258, к.2, стр.1',
      text: 'Санкт-Петербург, г. Санкт-Петербург, п. Шушары, Московское шоссе, дом 258, к.2, стр.1',
      lat: '59.755948',
      lon: '30.467351',
    },
    contact_phone: '+79218898612',
    organization: {
      id: '289375',
      logo: 'https://ucare.timepad.ru/9666547e-d590-496e-beaf-44d411dc7a31/-/preview/308x600/-/format/jpeg/',
      name: 'Библиотечный центр "ЛИСТ"',
      description:
        'Санкт-Петербургское государственное бюджетное учреждение\n«Территориальная централизованная библиотечная система Пушкинского района»',
      pdAddress:
        'г. Санкт-Петербург, пос. Шушары, Московское шоссе, дом 258, к.2, стр.1',
      pdEmail: 'filial05@cbspushkin.spb.ru',
      inn: null,
      ogrn: null,
      workingTime: '11:00 - 19:00',
      shareLink: null,
      poster:
        'https://ucare.timepad.ru/29375962-40e6-43d3-bc48-528eae7cbb28/-/preview/308x600/-/format/jpeg/-/format/jpeg/poster_org_289375.jpg',
      socials: [
        {
          name: 'vk',
          url: 'https://vk.com/list_biblioteka',
        },
        {
          name: 'facebook',
          url: '',
        },
        {
          name: 'twitter',
          url: '',
        },
        {
          name: 'telegram',
          url: '',
        },
        {
          name: 'instagram',
          url: '',
        },
        {
          name: 'web',
          url: '',
        },
      ],
      subscribers: 5,
      eventCount: null,
      isFavorite: false,
      contact_phone: '+79218898612',
    },
    isFavorite: false,
    order_mail: null,
    rating: null,
    startDateUnknown: false,
  },
  {
    id: '2406305',
    parentId: '',
    status: 'ok',
    recurringStatus: 'ok',
    hits: '8787',
    title: 'Экскурсия  для детей «Сказки нашей звезды»',
    isAdvertisement: false,
    isRepeated: false,
    GAID: null,
    startDate: '2023-05-06 16:00:00',
    endDate: '2023-05-06 17:30:00',
    minPrice: null,
    maxPrice: null,
    ordersNumber: 0,
    ticketsNumber: 0,
    repeatedData: {
      count: null,
      nearest: null,
      furthest: null,
    },
    ofertaLink: 'https://gaoran.timepad.ru/event/oferta/2406305/',
    allowRegistration: false,
    categories: ['379'],
    address: {
      city: 'Санкт-Петербург',
      street: 'Пулковское шоссе, д.65, к.1',
      text: 'Санкт-Петербург, Пулковское шоссе, д.65, к.1',
      lat: '59.770970',
      lon: '30.331775',
    },
    contact_phone: '+79312662887',
    organization: {
      id: '49842',
      logo: 'https://ucare.timepad.ru/c4e14c80-674f-43d5-8030-992105ddab86/',
      name: 'ФГБУН Главная (Пулковская) астрономическая обсерватория РАН',
      description:
        'Главная (Пулковская) астрономическая обсерватория Российской академии наук была основана в 1839 году по указу императора Николая  I и построена по проекту видного российского архитектора Александра Брюллова.\nГлавной составляющей интересной экскурсионной программы для посетителей Пулковской обсерватории является её Астрономический музей, экспонаты которого отражают историю развития российской астрономии XIX-XX веков. Музей расположен в Круглом и Меридианном залах Главного здания обсерватории.\nПервый музей Пулковской обсерватории («Музей старинных инструментов») был основан ещё в 1884 году и включал более 100 астрономических инструментов XVIII-XIX веков. Однако в годы Великой Отечественной войны многие экспонаты музея погибли. Настоящий музей и его экспозиция были заново возрождены уже в послевоенное время в 1967 году. Сегодня посетители могут ознакомиться с уникальными экспонатами музея - геодезическими инструментами, измерительной и вычислительной техникой, с оптикой крупнейших телескопов XIX-XX веков, собранием астрономических часов, портретами астрономов и ученых прошлых веков; увидеть центр Круглого зала, через который проходит знаменитый Пулковский меридиан.\nЭкскурсионная программа включает также знакомство посетителей с различными инструментами Обсерватории – телескопом-рефрактором на Центральной башне Главного здания, Большим Пулковским радиотелескопом, Солнечным телескопом, Нормальным астрографом, 26-дюймовым рефрактором и парком обсерватории. Ежегодно Обсерваторию посещает около 18 тысяч экскурсантов и гостей Санкт-Петербурга.\nГлавная (Пулковская) астрономическая обсерватория Российской Академии наук, оставаясь крупнейшим астрономическим учреждением России, Указом Президента Российской Федерации от 1998 года была включена в свод особо ценных объектов культурного наследия народов Российской Федерации и вошла в Список объектов всемирного наследия, находящихся под охраной ЮНЕСКО.\n\n',
      pdAddress: 'г Санкт-Петербург, Пулковское шоссе, д 65 к 1',
      pdEmail: 'pulkovoexc@gmail.com',
      inn: '7810207327',
      ogrn: '1037821018421',
      workingTime: '11:00 - 17:00',
      shareLink: null,
      poster: null,
      socials: [
        {
          name: 'vk',
          url: 'https://vk.com/pulex',
        },
        {
          name: 'facebook',
          url: '',
        },
        {
          name: 'twitter',
          url: '',
        },
        {
          name: 'telegram',
          url: '',
        },
        {
          name: 'instagram',
          url: '',
        },
        {
          name: 'web',
          url: 'http://www.gaoran.ru/',
        },
      ],
      subscribers: 157,
      eventCount: null,
      isFavorite: false,
      contact_phone: '+79312662887',
    },
    isFavorite: false,
    order_mail: false,
    rating: null,
    startDateUnknown: false,
  },
  {
    id: '2385992',
    parentId: '',
    status: 'ok',
    recurringStatus: 'ok',
    hits: '150',
    title: 'Концерт "Песни военных лет"',
    isAdvertisement: false,
    isRepeated: false,
    GAID: null,
    startDate: '2023-05-06 16:00:00',
    endDate: '2023-05-06 17:00:00',
    minPrice: 0,
    maxPrice: 0,
    ordersNumber: 0,
    ticketsNumber: 0,
    repeatedData: {
      count: null,
      nearest: null,
      furthest: null,
    },
    ofertaLink:
      'https://tsentralnaya-biblio-2021.timepad.ru/event/oferta/2385992/',
    allowRegistration: true,
    categories: ['460'],
    address: {
      city: 'Санкт-Петербург',
      street: 'ул. Варшавская, д. 37, к.1',
      text: 'Санкт-Петербург, ул. Варшавская, д. 37, к.1',
      lat: '59.859818',
      lon: '30.313541',
    },
    contact_phone: '+79119861044',
    organization: {
      id: '256831',
      logo: 'https://ucare.timepad.ru/468e0de2-7b3e-4e95-aab4-4a4ed304dbb7/-/preview/308x600/-/format/jpeg/',
      name: 'Центральная библиотека им. К.Г.Паустовского',
      description:
        '  Центральная библиотека имени К. Г. Паустовского – территория словесности. Статус библиотеки определяет разнообразный характер социокультурной деятельности, но приоритетным является изучение и продвижение мировой классической литературы, лучших современных писателей. Особое внимание уделяется жизни и творчеству Константина Георгиевича Паустовского, чье имя библиотека носит с 1997 года.\n     Здесь проходят творческие встречи, литературно-музыкальные вечера, выставки, мастер -классы. Центральная библиотека является постоянным участником городских фестивалей и акций: «Читай всегда, читай везде!», «Как пройти в библиотеку?» «Петербургские разночтения», «Книжные аллеи», «Живые улицы».',
      pdAddress: 'Санкт-Петербург, ул. Варшавская д.37, к.1',
      pdEmail: 'paustovsky@cbs-msk.ru',
      inn: null,
      ogrn: null,
      workingTime: '10:00 - 21:00',
      shareLink: null,
      poster:
        'https://ucare.timepad.ru/4cd08403-c34c-45b8-98a6-bfa97fd6a193/-/preview/308x600/-/format/jpeg/-/format/jpeg/poster_org_256831.jpg',
      socials: [
        {
          name: 'vk',
          url: 'https://vk.com/bibliolight',
        },
        {
          name: 'facebook',
          url: '',
        },
        {
          name: 'twitter',
          url: '',
        },
        {
          name: 'telegram',
          url: '',
        },
        {
          name: 'instagram',
          url: 'https://www.instagram.com/lib_paustovsky/https://ucare.timepad.ru/06925bc2-476a-40a4-b8a6-8ccb14a3a75d/-/preview/308x600/-/format/jpeg/-/preview/308x600/-/format/jpeg/logo_org_256831.jpg',
        },
        {
          name: 'web',
          url: 'https://www.cbs-msk.ru/centralnaya-biblioteka',
        },
      ],
      subscribers: 4,
      eventCount: null,
      isFavorite: false,
      contact_phone: '+79119861044',
    },
    isFavorite: false,
    order_mail: null,
    rating: null,
    startDateUnknown: false,
  },
  {
    id: '2408422',
    parentId: '',
    status: 'ok',
    recurringStatus: 'ok',
    hits: '46',
    title: 'Арт-вечеринка в "Фуд Парк Норд"',
    isAdvertisement: false,
    isRepeated: false,
    GAID: null,
    startDate: '2023-05-06 16:00:00',
    endDate: '2023-05-06 17:30:00',
    minPrice: 600,
    maxPrice: 600,
    ordersNumber: 0,
    ticketsNumber: 0,
    repeatedData: {
      count: null,
      nearest: null,
      furthest: null,
    },
    ofertaLink: 'https://evropa.timepad.ru/event/oferta/2408422/',
    allowRegistration: true,
    categories: ['525'],
    address: {
      city: 'Санкт-Петербург',
      street: 'ТРК Норд, 3-й этаж\r\nпр. Просвещения, 19 лит А',
      text: 'Санкт-Петербург, ТРК Норд, 3-й этаж\r\nпр. Просвещения, 19 лит А',
      lat: '60.052703',
      lon: '30.331202',
    },
    contact_phone: '+79319614666',
    organization: {
      id: '335143',
      logo: 'https://ucare.timepad.ru/7c26c0f5-0fbe-4e3e-a7d5-87277187dd2b/-/preview/308x600/-/format/jpeg/',
      name: 'Фуд Парк Норд',
      description: '',
      pdAddress:
        '194356, 194356, Г.Санкт-Петербург, ВН.ТЕР.Г. МУНИЦИПАЛЬНЫЙ ОКРУГ ШУВАЛОВО-ОЗЕРКИ, ПР-КТ ПРОСВЕЩЕНИЯ, Д. 19, ЛИТЕРА А, ПОМЕЩ. 1-Н, ПОМЕЩ. 909',
      pdEmail: 'k.shavykin@foodparknord.ru',
      inn: '7838096656',
      ogrn: '1217800140073',
      workingTime: '10:00 - 22:00',
      shareLink: null,
      poster:
        'https://ucare.timepad.ru/2c71e82e-0597-4954-ae6a-80542f65628b/-/preview/308x600/-/format/jpeg/-/format/jpeg/poster_org_335143.jpg',
      socials: [
        {
          name: 'vk',
          url: '',
        },
        {
          name: 'facebook',
          url: '',
        },
        {
          name: 'twitter',
          url: '',
        },
        {
          name: 'telegram',
          url: '',
        },
        {
          name: 'instagram',
          url: '',
        },
        {
          name: 'web',
          url: 'https://foodparknord.ru/',
        },
      ],
      subscribers: 0,
      eventCount: null,
      isFavorite: false,
      contact_phone: '+79319614666',
    },
    isFavorite: false,
    order_mail: null,
    rating: null,
    startDateUnknown: false,
  },
  {
    id: '2409621',
    parentId: '',
    status: 'ok',
    recurringStatus: 'ok',
    hits: '77',
    title: 'Открытое занятие «Художники-космисты: спираль времени»',
    isAdvertisement: false,
    isRepeated: false,
    GAID: null,
    startDate: '2023-05-02 17:00:00',
    endDate: null,
    minPrice: 0,
    maxPrice: 0,
    ordersNumber: 0,
    ticketsNumber: 0,
    repeatedData: {
      count: null,
      nearest: null,
      furthest: null,
    },
    ofertaLink: 'https://gbu-dmvo.timepad.ru/event/oferta/2409621/',
    allowRegistration: true,
    categories: ['525'],
    address: {
      city: 'Санкт-Петербург',
      street: 'Большой проспект Васильевского острова, 65',
      text: 'Санкт-Петербург, Большой проспект Васильевского острова, 65',
      lat: '59.934979',
      lon: '30.266569',
    },
    contact_phone: '+79500158855',
    organization: {
      id: '259733',
      logo: 'https://ucare.timepad.ru/476e8484-a250-4fc2-a1d5-3adeb91d4de7/-/preview/308x600/-/format/jpeg/',
      name: 'ГБУ ДМВО ',
      description: '',
      pdAddress: 'Санкт-Петербург, Большой проспект Васильевского острова 65',
      pdEmail: 'dmvo_orgmass@bk.ru',
      inn: null,
      ogrn: null,
      workingTime: '10:00 - 18:00',
      shareLink: null,
      poster: null,
      socials: [
        {
          name: 'vk',
          url: 'https://vk.com/dom65',
        },
        {
          name: 'facebook',
          url: '',
        },
        {
          name: 'twitter',
          url: '',
        },
        {
          name: 'telegram',
          url: '',
        },
        {
          name: 'instagram',
          url: 'https://instagram.com/dmvo65',
        },
        {
          name: 'web',
          url: 'http://new.доммолодежи.рф/',
        },
      ],
      subscribers: 7,
      eventCount: null,
      isFavorite: false,
      contact_phone: '+79500158855',
    },
    isFavorite: false,
    order_mail: null,
    rating: null,
    startDateUnknown: false,
  },
  {
    id: '2406652',
    parentId: '',
    status: 'ok',
    recurringStatus: 'ok',
    hits: '117',
    title: 'Экскурсия в Эрмитаж с искусствоведом. Первое знакомство',
    isAdvertisement: false,
    isRepeated: false,
    GAID: 'G-7N1543B5KC',
    startDate: '2023-05-06 17:30:00',
    endDate: '2023-05-06 19:30:00',
    minPrice: 1500,
    maxPrice: 2500,
    ordersNumber: 0,
    ticketsNumber: 0,
    repeatedData: {
      count: null,
      nearest: null,
      furthest: null,
    },
    ofertaLink: 'https://sloi-peterburga.timepad.ru/event/oferta/2406652/',
    allowRegistration: true,
    categories: ['461'],
    address: {
      city: 'Санкт-Петербург',
      street: 'Дворцовая пл, 2',
      text: 'Санкт-Петербург, Дворцовая пл, 2',
      lat: '59.940082',
      lon: '30.312814',
    },
    contact_phone: '+79618020005',
    organization: {
      id: '323691',
      logo: 'https://ucare.timepad.ru/c4c7a75f-6656-4c7b-8601-785c4029096c/-/preview/308x600/-/format/jpeg/',
      name: 'SLOI Петербурга',
      description:
        'На экскурсию в музей за смыслом!\nЭкскурсии по Петербургу в мини-группах с философами, искусствоведами, историками и журналистами.',
      pdAddress: '196240, г Санкт-Петербург, ул Варшавская, д 71, кв 46',
      pdEmail: 'sloi.piter@gmail.com',
      inn: '7820316156',
      ogrn: '1089847354794',
      workingTime: '10:00 - 20:00',
      shareLink: null,
      poster:
        'https://ucare.timepad.ru/83666a58-2e07-435c-a901-96b51cf8c77f/-/preview/308x600/-/format/jpeg/-/format/jpeg/poster_org_323691.jpg',
      socials: [
        {
          name: 'vk',
          url: 'https://vk.com/sloi.piter',
        },
        {
          name: 'facebook',
          url: '',
        },
        {
          name: 'twitter',
          url: '',
        },
        {
          name: 'telegram',
          url: 'https://t.me/sloipiter',
        },
        {
          name: 'instagram',
          url: '',
        },
        {
          name: 'web',
          url: 'https://sloipiter.ru/',
        },
      ],
      subscribers: 5,
      eventCount: null,
      isFavorite: false,
      contact_phone: '+79618020005',
    },
    isFavorite: false,
    order_mail: false,
    rating: null,
    startDateUnknown: false,
  },
  {
    id: '2397544',
    parentId: '',
    status: 'ok',
    recurringStatus: 'ok',
    hits: '1195',
    title: 'Мода и кино: 1960-е',
    isAdvertisement: false,
    isRepeated: false,
    GAID: null,
    startDate: '2023-05-06 18:00:00',
    endDate: '2023-05-06 19:30:00',
    minPrice: 0,
    maxPrice: 0,
    ordersNumber: 0,
    ticketsNumber: 0,
    repeatedData: {
      count: null,
      nearest: null,
      furthest: null,
    },
    ofertaLink: 'https://oxta8.timepad.ru/event/oferta/2397544/',
    allowRegistration: true,
    categories: ['374'],
    address: {
      city: 'Санкт-Петербург',
      street: 'Большеохтинский проспект, дом 8',
      text: 'Санкт-Петербург, Большеохтинский проспект, дом 8',
      lat: '59.951146',
      lon: '30.409212',
    },
    contact_phone: '+79045514757',
    organization: {
      id: '171605',
      logo: 'https://ucare.timepad.ru/1c714536-b029-42ab-8803-222c7b09efbe/-/preview/308x600/-/format/jpeg/',
      name: 'Библиотека им. В.В. Маяковского, Охта-8',
      description: '',
      pdAddress: 'Санкт-Петербург, Большеохтинский проспект, дом 8',
      pdEmail: 'bigoxta@gmail.com',
      inn: null,
      ogrn: null,
      workingTime: '10:00 - 22:00',
      shareLink: null,
      poster:
        'https://ucare.timepad.ru/62e9175e-dbd9-4dda-8538-3b91eda2a293/-/preview/308x600/-/format/jpeg/-/format/jpeg/poster_org_171605.jpg',
      socials: [
        {
          name: 'vk',
          url: 'https://vk.com/bigoxta8',
        },
        {
          name: 'facebook',
          url: '',
        },
        {
          name: 'twitter',
          url: '',
        },
        {
          name: 'telegram',
          url: '',
        },
        {
          name: 'instagram',
          url: '',
        },
        {
          name: 'web',
          url: '',
        },
      ],
      subscribers: 152,
      eventCount: null,
      isFavorite: false,
      contact_phone: '+79045514757',
    },
    isFavorite: false,
    order_mail: null,
    rating: null,
    startDateUnknown: false,
  },
  {
    id: '2401141',
    parentId: '',
    status: 'ok',
    recurringStatus: 'ok',
    hits: '607',
    title: 'Спектакль «Сторож снов»',
    isAdvertisement: false,
    isRepeated: false,
    GAID: 'G-XC2R6QLXK4\n',
    startDate: '2023-05-06 18:00:00',
    endDate: '2023-05-06 19:00:00',
    minPrice: 800,
    maxPrice: 1500,
    ordersNumber: 0,
    ticketsNumber: 0,
    repeatedData: {
      count: null,
      nearest: null,
      furthest: null,
    },
    ofertaLink: 'https://upsala-circus-spb.timepad.ru/event/oferta/2401141/',
    allowRegistration: true,
    categories: ['525'],
    address: {
      city: 'Санкт-Петербург',
      street: 'Свердловская набережная, 44Ю',
      text: 'Санкт-Петербург, Свердловская набережная, 44Ю',
      lat: '59.961224',
      lon: '30.402052',
    },
    contact_phone: '+79219262577',
    organization: {
      id: '167346',
      logo: 'https://ucare.timepad.ru/165871b1-3231-4d09-a47f-05d21a5d48cf/',
      name: 'Упсала-Цирк',
      description: '',
      pdAddress:
        '195027, г Санкт-Петербург, Свердловская наб, д 44 литер ю, пом 101',
      pdEmail: 'grant@upsalacircus.ru',
      inn: '7811154195',
      ogrn: '1087800004434',
      workingTime: '10:00 - 18:00',
      shareLink: null,
      poster:
        'https://ucare.timepad.ru/287f22ff-3f5e-477c-8a68-e4a00548099b/-/preview/308x600/-/format/jpeg/-/format/jpeg/poster_org_167346.jpg',
      socials: [
        {
          name: 'vk',
          url: 'https://vk.com/upsalacircus',
        },
        {
          name: 'facebook',
          url: 'https://www.facebook.com/UpsalaCircus',
        },
        {
          name: 'twitter',
          url: '',
        },
        {
          name: 'telegram',
          url: '',
        },
        {
          name: 'instagram',
          url: 'https://www.instagram.com/upsalacircus/',
        },
        {
          name: 'web',
          url: '',
        },
      ],
      subscribers: 24,
      eventCount: null,
      isFavorite: false,
      contact_phone: '+79219262577',
    },
    isFavorite: false,
    order_mail: null,
    rating: null,
    startDateUnknown: false,
  },
  {
    id: '2389588',
    parentId: '',
    status: 'ok',
    recurringStatus: 'ok',
    hits: '189',
    title: '«Зеленый лекторий: От царских огородов до парковых парадизов»',
    isAdvertisement: false,
    isRepeated: false,
    GAID: null,
    startDate: '2023-05-06 18:00:00',
    endDate: '2023-05-06 19:30:00',
    minPrice: 0,
    maxPrice: 0,
    ordersNumber: 0,
    ticketsNumber: 0,
    repeatedData: {
      count: null,
      nearest: null,
      furthest: null,
    },
    ofertaLink:
      'https://tsentr-peterburgovedeniya.timepad.ru/event/oferta/2389588/',
    allowRegistration: true,
    categories: ['525'],
    address: {
      city: 'Санкт-Петербург',
      street: 'наб. р. Фонтанки, 44, 1 этаж (над цоколем), Медиахолл',
      text: 'Санкт-Петербург, наб. р. Фонтанки, 44, 1 этаж (над цоколем), Медиахолл',
      lat: '59.932311',
      lon: '30.343734',
    },
    contact_phone: '+78122644630',
    organization: {
      id: '254656',
      logo: 'https://ucare.timepad.ru/b991478f-300b-4960-9ae8-858af6d60167/-/preview/308x600/-/format/jpeg/',
      name: 'Центр петербурговедения (Маяковка)',
      description:
        'Главный краеведческий центр Петербурга. Находимся в самом сердце Петербурга - на третьем этаже Невского пр. 20. ',
      pdAddress: 'СПб, Невский пр., 20, 3 этаж',
      pdEmail: 'm.tychininama@gmail.com',
      inn: null,
      ogrn: null,
      workingTime: '11:00 - 20:00',
      shareLink: null,
      poster:
        'https://ucare.timepad.ru/75397d04-68d5-4362-8094-c1acbb06b080/-/preview/308x600/-/format/jpeg/-/format/jpeg/poster_org_254656.jpg',
      socials: [
        {
          name: 'vk',
          url: 'https://vk.com/mayaklibspb',
        },
        {
          name: 'facebook',
          url: '',
        },
        {
          name: 'twitter',
          url: '',
        },
        {
          name: 'telegram',
          url: '',
        },
        {
          name: 'instagram',
          url: 'https://www.instagram.com/peterburgoved/',
        },
        {
          name: 'web',
          url: 'http://mirpeterburga.ru/',
        },
      ],
      subscribers: 75,
      eventCount: null,
      isFavorite: false,
      contact_phone: '+78122644630',
    },
    isFavorite: false,
    order_mail: null,
    rating: null,
    startDateUnknown: false,
  },
  {
    id: '2409160',
    parentId: '',
    status: 'ok',
    recurringStatus: 'ok',
    hits: '28',
    title: 'Мастер-класс по сценической пластике в «Фуд Парк Меркурий».',
    isAdvertisement: false,
    isRepeated: false,
    GAID: null,
    startDate: '2023-05-02 18:00:00',
    endDate: '2023-05-02 20:00:00',
    minPrice: 0,
    maxPrice: 0,
    ordersNumber: 0,
    ticketsNumber: 0,
    repeatedData: {
      count: null,
      nearest: null,
      furthest: null,
    },
    ofertaLink: 'https://fud-park-merkuriy.timepad.ru/event/oferta/2409160/',
    allowRegistration: true,
    categories: ['379'],
    address: {
      city: 'Санкт-Петербург',
      street: 'Россия, Санкт-Петербург, улица Савушкина, 141',
      text: 'Санкт-Петербург, Россия, Санкт-Петербург, улица Савушкина, 141',
      lat: '59.990899',
      lon: '30.205789',
    },
    contact_phone: '+79311031717',
    organization: {
      id: '281061',
      logo: 'https://ucare.timepad.ru/5be460c3-32c2-4d3b-a9e6-8f25b3754af3/-/preview/308x600/-/format/jpeg/',
      name: 'Фуд Парк Меркурий',
      description: '',
      pdAddress:
        '197374, г Санкт-Петербург, ул Савушкина, д 141 литера а, помещ 431 офис 1Н',
      pdEmail: 'info@foodparkmercury.ru',
      inn: '7814758484',
      ogrn: '1197847109349',
      workingTime: '10:00 - 22:00',
      shareLink: null,
      poster: null,
      socials: [
        {
          name: 'vk',
          url: '',
        },
        {
          name: 'facebook',
          url: '',
        },
        {
          name: 'twitter',
          url: '',
        },
        {
          name: 'telegram',
          url: '',
        },
        {
          name: 'instagram',
          url: '',
        },
        {
          name: 'web',
          url: '',
        },
      ],
      subscribers: 8,
      eventCount: null,
      isFavorite: false,
      contact_phone: '+79311031717',
    },
    isFavorite: false,
    order_mail: null,
    rating: null,
    startDateUnknown: false,
  },
];
